export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_START = 'LOGIN_START';

export const LOGOUT_USER = 'LOGOUT_USER';

export const UPCOMING_EVENTS_LOADING = 'UPCOMING_EVENTS_LOADING';
export const UPCOMING_EVENTS_SUCCESS = 'UPCOMING_EVENTS_SUCCESS';
export const UPCOMING_EVENTS_FAILED = 'UPCOMING_EVENTS_FAILED';

export const LIVE_EVENTS_LOADING = 'LIVE_EVENTS_LOADING';
export const LIVE_EVENTS_SUCCESS = 'LIVE_EVENTS_SUCCESS';
export const LIVE_EVENTS_FAILED = 'LIVE_EVENTS_FAILED';

export const SINGLE_EVENT_LOADING = 'SINGLE_EVENT_LOADING';
export const SINGLE_EVENT_SUCCESS = 'SINGLE_EVENT_SUCCESS';
export const SINGLE_EVENT_FAILED = 'SINGLE_EVENT_FAILED';

export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_FAILED = 'PROFILE_FAILED';
